baseURL = "https://til.damasukma.com/"
languageCode = "en-us"
title = "Today I Learned - Dama"
theme = "upgan"

summaryLength = 17
sectionPagesMenu = "main"

defaultContentLanguage = "en"

[pagination]
  pagerSize = 999

googleAnalytics = "G-KXD1G8P0DP"

enableEmoji = true
enableGitInfo = false
enableRobotsTXT = true
canonifyURLs = true

[module]
  [[module.imports]]
    path = "github.com/zuramai/upgan"

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
  description = "Dama's blog and daily writing about thoughts, tutorial, and a bit of theories. Dama's blog may help you to open your mind up."
  author = "Dama"
  faviconURL = "/favicon.ico"
  og_image = "/images/author/Dama.jpg"
  sitename = "Today I Learned - Dama"
  home_show_tags = true

[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    weight = 1

  [languages.id]
    languageName = "Indonesia"
    languageCode = "id"
    weight = 2

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Main Site"
    url = "https://damasukma.com"
    weight = 2

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4

  [markup.goldmark.renderer]
    unsafe= true

[services]
  [services.disqus]
    shortname = "blog-Dama"
